config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/page1'
  post 'welcome/page1'

  get 'welcome/verify'
  post 'welcome/verify'

  get 'welcome/failed_verify'
  post 'welcome/failed_verify'

  get 'welcome/confirm_who'
  post 'welcome/confirm_who'

  get 'welcome/upload_photo_option'
  post 'welcome/upload_photo_option'

  get 'welcome/webchat_question'
  post 'welcome/webchat_question'

  get 'welcome/phone_question'
  post 'welcome/phone_question'

  get 'welcome/phone_access'
  post 'welcome/phone_access'

  get 'welcome/internal_portal'
  post 'welcome/internal_portal'

  get 'welcome/generated_code'
  post 'welcome/generated_code'

  get 'welcome/upload_photo'
  post 'welcome/upload_photo'

  get 'welcome/photo_confirmed'
  post 'welcome/photo_confirmed'


  get 'welcome/webchat'
  post 'welcome/webchat'

  get 'welcome/enter_bank_details'
  post 'welcome/enter_bank_details'

  get 'welcome/success'
  post 'welcome/success'

  get 'welcome/upload_photo'
  post 'welcome/upload_photo'

  get 'welcome/page2'
  post 'welcome/page2'

  get 'welcome/facebook_login'
  post 'welcome/facebook_login'

  get 'welcome/login'
  post 'welcome/login'

  get 'welcome/login_or_signup'
  post 'welcome/login_or_signup'

  get 'welcome/used_before'
  post 'welcome/used_before'

  get 'welcome/enter_your_details'
  post 'welcome/enter_your_details'

  get 'welcome/enter_mobile'
  post 'welcome/enter_mobile'

  get 'welcome/enter_access_code'
  post 'welcome/enter_access_code'


  get 'welcome/two_step'
  post 'welcome/two_step'

  get 'welcome/success_two_step'
  post 'welcome/success_two_step'

  get 'welcome/confirm_who'
  post 'welcome/confirm_who_post'

  get 'welcome/facebook_data'
  post 'welcome/facebook_data'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  around_action :handle_post

  def page1
  end

  def page1_post

    redirect_to welcome_page2_path
  end

  def webchat_question
  end

  def webchat_question_post

    if !params[:webchat].blank? && params[:webchat] == 'yes'
      redirect_to welcome_webchat_path

    else
      redirect_to welcome_phone_question_path
    end


  end

  def phone_question
  end

  def phone_question_post

    if !params[:phone].blank? && params[:phone] == 'yes'
      redirect_to welcome_phone_access_path

    else
      redirect_to welcome_webchat_question_path
    end
  end

  def phone_access
  end

  def phone_access_post

    redirect_to welcome_internal_portal_path
  end

  def internal_portal
  end

  def internal_portal_post

    redirect_to welcome_generated_code_path
  end

  def generated_code
  end

  def generated_code_post
    redirect_to welcome_enter_access_code_path
  end



  def webchat
  end

  def webchat_post

    redirect_to welcome_internal_portal_path
  end

  def enter_bank_details
  end

  def enter_bank_details_post
  end





  def confirm_who
  end

  def confirm_who_post
    redirect_to welcome_upload_photo_option_path
  end

  def page2
  end

  def page2_post

    redirect_to welcome_login_or_signup_path
  end

  def photo_confirmed
  end

  def photo_confirmed_post
    redirect_to welcome_enter_bank_details_path
  end


  def upload_photo_option
  end

  def upload_photo_option_post
    puts "***********************    photo is not blank  #{params[:photo]}"
    if !params[:photo].blank? && params[:photo] == 'yes'
      puts "***********************    photo is not blank  #{params[:photo]}"
      redirect_to welcome_upload_photo_path

    else
      redirect_to welcome_webchat_question_path
    end
  end

  def upload_photo
  end

  def upload_photo_post

    redirect_to welcome_photo_confirmed_path
  end



  def login
  end

  def login_post

    redirect_to welcome_verify_path
  end

  def enter_bank_details
  end

  def enter_bank_details_post
    redirect_to welcome_success_path
  end

  def verify
  end

  def verify_post
    redirect_to welcome_failed_verify_path
  end

  def failed_verify
  end

  def failed_verify_post

    redirect_to welcome_confirm_who_path
  end

  def login_or_signup
  end

  def login_or_signup_post

    redirect_to welcome_login_path
  end

  def enter_your_details
  end

  def enter_your_details_post

    redirect_to welcome_two_step_path
  end

  def used_before
  end

  def used_before_post

    redirect_to welcome_enter_your_details_path
  end

  def two_step
  end

  def two_step_post

    redirect_to welcome_enter_mobile_path
  end

  def enter_mobile
  end

  def enter_mobile_post
    redirect_to welcome_enter_access_code_path
  end

  def enter_access_code
  end

  def enter_access_code_post
    redirect_to welcome_enter_bank_details_path
  end

  def success
  end

  def success_post
  end

  def success_two_step
  end

  def success_two_step_post
    redirect_to welcome_confirm_who_path
  end

  def facebook_login
  end

  def facebook_login_post
    session.delete(:data)


    @application = session[:application]

    @data = Hash.new
    @data[:id] = params[:id]
    @data[:first_name] = params[:first_name]
    @data[:last_name] = params[:last_name]
    @data[:age_range_min] = params[:age_range_min]
    @data[:email] = params[:email]
    @data[:updated_time] = params[:updated_time]
    @data[:picture] = params[:picture]

    session[:data] = @data

    redirect_to welcome_facebook_data_path
  end

  def facebook_data
    @data = session[:data]

  end

  def facebook_data_post
  end




  private

  def handle_post
    if request.post? && self.respond_to?( "#{action_name}_post" )
      self.public_send "#{action_name}_post"
    end
    yield unless performed?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
- content_for :head do
  = stylesheet_link_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

- content_for :page_title do
  GOV.UK - Leeds hack

- content_for :logo_link_title do
  Leeds hack

- content_for :global_header_text do
  GOV.UK

- content_for :homepage_url do
  https://www.gov.uk/

- content_for :footer_support_links do
  %h2.visually-hidden Support links
  %ul
    %li
      = link_to "Cookie Policy", target: "_blank"
    %li
      = link_to "Terms and Conditions", target: "_blank"
    %li
      = link_to "Privacy Policy", target: "_blank"

- content_for :header_class do
  with-proposition

-# Uncomment if you want to use the proposition menu
-#- content_for :header_class do
-# with-proposition
- content_for :proposition_header do
  .header-proposition
    .content
      %nav{id: "proposition-menu"}
        %a{id: "proposition-name", href: root_path } Leeds identity hack

- content_for :content do
  %main{ id: "content", role: "main"}
    .phase-banner
      %p
        %strong.phase-tag ALPHA
        %span
          This is a new service – your
          %a{ href:"#"} feedback
          will help us to improve it.

      .userBar{ style: "text-align: right"}
        - current_action = action_name



    = yield



= render template: 'layouts/govuk_template'

app/views/welcome/confirm_who.html.haml
= render "back_link"


%h1.heading-large You still need to prove who you are

%p To do this you will need
%p Driving licence
%p Bank account

= form_tag welcome_confirm_who_path do




  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/enter_access_code.html.haml
= render "back_link"


%h1.heading-large Enter your access code

%p Enter your access code below and press continue.

= form_tag welcome_enter_access_code_path do

  .form-group{:class => ("error" if (!@errors.blank?) && (@errors.key? (:name)))}
    .form-label 
    - if (!@errors.blank?) && (@errors.key? (:name))
      .error-message
        = @errors[:name]
    = text_field_tag :name, params[:name], class: 'form-control', maxlength: "250"



  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/facebook_login.html.haml
= render "back_link"

- if ! @errors.blank?
  .error-summary
    %h1.heading-medium.error-summary-heading
      There was a problem
    %p Please amend the following details:
    %ul.error-summary-list
      - @errors.each do |k,v|
        %li.error-message
          %a{href: "#" + k.to_s, "data-turbolinks" => "false"} #{v}

%h1.heading-large Facebook login

%fb:login-button{scope: "public_profile,email", onlogin: "checkLoginState();", "data-size": "xlarge", "data-show-faces": "false", "data-auto-logout-link": "true", "data-max-rows": "5"}

=# link_to "Logout", "", :onclick => "logout(); return false"

=# link_to "Login", "", :onclick => "login(); return false"

.fb-login-button= content_tag :div, nil, "data-max-rows": "5", "data-size": "xlarge", "data-show-faces": "true", "data-auto-logout-link": "true"

%p
  = content_tag :div, nil, id: "status"

= content_tag :div, nil, id: "fb-root"

= form_tag welcome_facebook_login_path do
  = hidden_field_tag :id
  = hidden_field_tag :first_name
  = hidden_field_tag :last_name
  = hidden_field_tag :age_range_min
  = hidden_field_tag :email
  = hidden_field_tag :updated_time
  = hidden_field_tag :picture

  %p.lede After logging into your facebook account click continue to see the data retrieved from facebook 

  %p= submit_tag 'Continue', class: 'button'
:javascript
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1793521167634673',
    cookie     : true,  // enable cookies to allow the server to access
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.8' // use graph api version 2.8
  });

  // Now that we've initialized the JavaScript SDK, we call
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);


      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });

    FB.api('/me', {fields: 'id,first_name,last_name,age_range,email,updated_time,picture'}, function(response) {
      document.getElementById("id").value = response.id;
      document.getElementById("first_name").value = response.first_name;
      document.getElementById("last_name").value = response.last_name;
      document.getElementById("age_range_min").value = response.age_range.min;
      document.getElementById("email").value = response.email;
      document.getElementById("updated_time").value = response.updated_time;
      document.getElementById("picture").value = response.picture.data.url;
      console.log(response);
    });
  }

  function logout() {
    FB.logout(function(response) {
    // user is now logged out
      statusChangeCallback(response);
      console.log('logging the user out');
    });
  }

  function login() {
    FB.login(function(response) {
    // user is now logged out
      statusChangeCallback(response);
      console.log('logging the user in');
    }, { auth_type: 'reauthenticate' });
  }

app/views/welcome/generated_code.html.haml
= render "back_link"

%h1.heading-large Please inform the customer of the generated code

.govuk-box-highlight
  %h1.bold-large 32324467
  %p


= form_tag welcome_generated_code_path do




  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/index.html.haml
%h1.heading-large
  Leeds identity hack

  %p.lede Click on start now to begin.....


  %p= link_to 'Start now', welcome_login_or_signup_path,class: 'button button-start'


.grid-row

  .column-two-thirds

app/views/welcome/login.html.haml
= render "back_link"

%h1.heading-large
  Login

  %p.lede Please enter your driver number


= form_tag welcome_login_path do

  .form-group{:class => ("error" if (!@errors.blank?) && (@errors.key? (:name)))}
    .form-label driver number
    - if (!@errors.blank?) && (@errors.key? (:name))
      .error-message
        = @errors[:name]
    = text_field_tag :driver_number, params[:driver_number], class: 'form-control', maxlength: "250"


  %p= submit_tag 'login', class: 'button'

app/views/welcome/login_or_signup.html.haml
%h1.heading-large
  login or sign up

  %p.lede would you like to login or sign up

= form_tag welcome_login_or_signup_path do

  .form-group{ class: !@errors.blank? && @errors[:end_user] ? "error" : ""}

    - if (!@errors.blank?) && (@errors.key? (:login_or_signup))
      .error-message
        = @errors[:login_or_signup]

    %fieldset.inline
      %legend.visuallyhidden{ id: "login_or_signup" } would you like to login or sign up
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-1" do
        = radio_button_tag :login_or_signup, 'login', nil, id: "radio-1"
        Login
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-2" do
        = radio_button_tag :login_or_signup, 'signup', nil, id: "radio-2"
        signup

    %br

  .form-group
    %p= submit_tag 'Continue', class: 'button'

:javascript
  $(document).ready(function () {
    // Use GOV.UK selection-buttons.js to set selected
    // and focused states for block labels
    var $blockLabels = $(".block-label input[type='radio'], .block-label input[type='checkbox']")
    new GOVUK.SelectionButtons($blockLabels) // eslint-disable-line
    // Use GOV.UK shim-links-with-button-role.js to trigger a link styled to look like a button,
    // with role="button" when the space key is pressed.
    GOVUK.shimLinksWithButtonRole.init()
    // Show and hide toggled content
    // Where .block-label uses the data-target attribute
    // to toggle hidden content
    var showHideContent = new GOVUK.ShowHideContent()
    showHideContent.init()
  });

app/views/welcome/page1.html.haml
= render "back_link"

- if ! @errors.blank?
  .error-summary
    %h1.heading-medium.error-summary-heading
      There was a problem
    %p Please amend the following details:
    %ul.error-summary-list
      - @errors.each do |k,v|
        %li.error-message
          %a{href: "#" + k.to_s, "data-turbolinks" => "false"} #{v}

%h1.heading-large Page 1

= form_tag welcome_page1_path do

  .form-group{:class => ("error" if (!@errors.blank?) && (@errors.key? (:name)))}
    .form-label Name
    - if (!@errors.blank?) && (@errors.key? (:name))
      .error-message
        = @errors[:name]
    = text_field_tag :name, params[:name], class: 'form-control', maxlength: "250"

  .form-group{:class => ("error" if (!@errors.blank?) && (@errors.key? (:phone_number_landline)))}
    .form-label Contact number
    - if (!@errors.blank?) && (@errors.key? (:phone_number))
      .error-message
        = @errors[:phone_number]
    = text_field_tag :phone_number, params[:phone_number], class: 'form-control', maxlength: "50"


  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/phone_access.html.haml
= render "back_link"

%h1.heading-large Access code
%p Please call the number below in order to obtain an access code.
%p Tel: 01234 3456789


= form_tag welcome_phone_access_path do




  %p= submit_tag 'Continue to internal portal', class: 'button'

app/views/welcome/photo_confirmed.html.haml
.govuk-box-highlight
  %h1.bold-large Photo match has been successful
  %p

= image_tag  "lee.jpg"

= form_tag welcome_photo_confirmed_path do




  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/success_two_step.html.haml
= render "back_link"


%h1.heading-large You have successfully set up 2-step verification

%p You'll be sent a new access code to your mobile phone every time you sign in


= form_tag welcome_success_two_step_path do




  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/upload_photo_option.html.haml
%h1.heading-large
  Do you have a photo licence

  %p.lede Would you like to upload a photo.
  %p.lede We would use this to confirm your identity

= form_tag welcome_upload_photo_option_path do

  .form-group{ class: !@errors.blank? && @errors[:end_user] ? "error" : ""}



    %fieldset
      %legend.visuallyhidden{ id: "login_or_signup" } would you like to login or sign up
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-1" do
        = radio_button_tag :photo, 'yes', nil, id: "radio-1"
        Upload a photo
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-2" do
        = radio_button_tag :photo, 'no', nil, id: "radio-2"
        I don't want to upload a photo

    %br

  .form-group
    %p= submit_tag 'Continue', class: 'button'

:javascript
  $(document).ready(function () {
    // Use GOV.UK selection-buttons.js to set selected
    // and focused states for block labels
    var $blockLabels = $(".block-label input[type='radio'], .block-label input[type='checkbox']")
    new GOVUK.SelectionButtons($blockLabels) // eslint-disable-line
    // Use GOV.UK shim-links-with-button-role.js to trigger a link styled to look like a button,
    // with role="button" when the space key is pressed.
    GOVUK.shimLinksWithButtonRole.init()
    // Show and hide toggled content
    // Where .block-label uses the data-target attribute
    // to toggle hidden content
    var showHideContent = new GOVUK.ShowHideContent()
    showHideContent.init()
  });

app/views/welcome/webchat.html.haml
= render "back_link"


%h1.heading-large Webchat
%p the webchat would take place here.......


= form_tag welcome_webchat_path do




  %p= submit_tag 'Continue', class: 'button'

app/views/welcome/webchat_question.html.haml
%h1.heading-large
  Would you like to use web chat


= form_tag welcome_webchat_question_path do

  .form-group{ class: !@errors.blank? && @errors[:end_user] ? "error" : ""}



    %fieldset
      %legend.visuallyhidden{ id: "login_or_signup" } would you like to login or sign up
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-1" do
        = radio_button_tag :webchat, 'webchat', nil, id: "radio-1"
        Use webchat
      = label_tag nil, class: "block-label selection-button-radio", for: "radio-2" do
        = radio_button_tag :webchat, 'webchat_no', nil, id: "radio-2"
        Don't use web chat

    %br

  .form-group
    %p= submit_tag 'Continue', class: 'button'

:javascript
  $(document).ready(function () {
    // Use GOV.UK selection-buttons.js to set selected
    // and focused states for block labels
    var $blockLabels = $(".block-label input[type='radio'], .block-label input[type='checkbox']")
    new GOVUK.SelectionButtons($blockLabels) // eslint-disable-line
    // Use GOV.UK shim-links-with-button-role.js to trigger a link styled to look like a button,
    // with role="button" when the space key is pressed.
    GOVUK.shimLinksWithButtonRole.init()
    // Show and hide toggled content
    // Where .block-label uses the data-target attribute
    // to toggle hidden content
    var showHideContent = new GOVUK.ShowHideContent()
    showHideContent.init()
  });